### ISSUE TITLE
Bundle command doesn't run

### ISSUE THREAD

**Issue by Slavrix** [Urigo/meteor-client-bundler#1]
Im following the updated whatsapp tutorial and when it comes to using the bundler it doesnt work on my system.
im building on windows 10 64bit.
ive tried with both a normal cmd windows and with admin
the same code and scripts and everything works on my macbook, so it seems to be a windows compatibility issue.
```
G:\gravity\clubapp\clubezyionicmeteor>meteor-client bundle
child_process.js:513
    throw err;
    ^

Error: spawnSync meteor ENOENT
    at exports._errnoException (util.js:1022:11)
    at spawnSync (child_process.js:468:20)
    at Object.execFileSync (child_process.js:505:13)
    at Object.bundle (C:\Users\nicholas\AppData\Roaming\npm\node_modules\meteor-client-bundler\bundler.js:38:3)
    at Command.<anonymous> (C:\Users\nicholas\AppData\Roaming\npm\node_modules\meteor-client-bundler\cli:37:13)
    at Command.listener (C:\Users\nicholas\AppData\Roaming\npm\node_modules\meteor-client-bundler\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\nicholas\AppData\Roaming\npm\node_modules\meteor-client-bundler\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\nicholas\AppData\Roaming\npm\node_modules\meteor-client-bundler\node_modules\commander\index.js:458:21)
```

**Comment by DAB0mB** [comment]
@Slavrix Do you have `meteor` CLI installed?

**Comment by Slavrix** [comment]
yes I do

**Comment by DAB0mB** [comment]
Ok, I took notes, I will try to fix it asap and I will let you know

**Comment by DAB0mB** [comment]
@Slavrix We've just released a new version with Windows support, can you please try it out? Tell me if it works now, thanks!

**Comment by Slavrix** [comment]
looks like its working to me.
nice job and thanks.
time to upgrade my projects.

**Comment by nanomo** [comment]
Had similar issue:

Windows 7 64 bits

node -v
v6.10.1
npm -v
4.4.4
Your system information:

Cordova CLI: 6.4.0
Gulp version: CLI version 3.9.1
Gulp local:
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.1.4
Ionic App Lib Version: 2.1.2
Ionic App Scripts Version: 1.2.5
OS: Windows 7 SP1
Node Version: v6.10.1

C:\apps\someapp>npm run meteor-client:bundle

ionic-hello-world@ meteor-client:bundle C:\apps\someapp
meteor-client bundle -s api
Created a new Meteor app in
'C:\Users\MALDIT~1\AppData\Local\Temp\tmp-20527S7sUIvnECrM'.

To run your new app:
cd C:\Users\MALDIT~1\AppData\Local\Temp\tmp-20527S7sUIvnECrM
meteor

If you are new to Meteor, try some of the learning resources here:
https://www.meteor.com/learn

meteor create --bare to create an empty app.
meteor create --full to create a scaffolded app.

Changes to your project's package version selections:

barbatus:typescript added, version 0.6.5_1
barbatus:typescript-compiler added, version 0.9.5
barbatus:typescript-runtime added, version 1.0.0

WARNING: The output directory is under your source tree.
Your generated files may get interpreted as source code!
Consider building into a different directory instead
meteor build ../output

C:\Users\malditowindows\AppData\Local.meteor\packages\meteor-tool\1.4.3_2\mt-os
.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:190

  throw error;
  ^
RangeError: Maximum call stack size exceeded
C:\Users\malditowindows\AppData\Roaming\npm\node_modules\meteor-client-bundler\n
ode_modules\execa\index.js:277
throw (result.error || new Error(result.stderr === '' ? result.s
tdout : result.stderr));
^

Error: null
at Function.module.exports.sync (C:\Users\malditowindows\AppData\Roaming\npm
\node_modules\meteor-client-bundler\node_modules\execa\index.js:277:26)
at Object.bundle (C:\Users\malditowindows\AppData\Roaming\npm\node_modules\m
eteor-client-bundler\lib\bundler.js:72:9)
at Command. (C:\Users\malditowindows\AppData\Roaming\npm\node_mod
ules\meteor-client-bundler\cli:37:13)
at Command.listener (C:\Users\malditowindows\AppData\Roaming\npm\node_module
s\meteor-client-bundler\node_modules\commander\index.js:301:8)
at emitTwo (events.js:106:13)
at Command.emit (events.js:191:7)
at Command.parseArgs (C:\Users\malditowindows\AppData\Roaming\npm\node_modul
es\meteor-client-bundler\node_modules\commander\index.js:615:12)
at Command.parse (C:\Users\malditowindows\AppData\Roaming\npm\node_modules\m
eteor-client-bundler\node_modules\commander\index.js:458:21)
at Object. (C:\Users\malditowindows\AppData\Roaming\npm\node_modu
les\meteor-client-bundler\cli:45:9)
at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ionic-hello-world@ meteor-client:bundle: meteor-client bundle -s api
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ionic-hello-world@ meteor-client:bundle script 'meteor-cl
ient bundle -s api'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! meteor-client bundle -s api
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.`
