### ISSUE TITLE
Error when building android

### ISSUE THREAD

**Issue by kokokenada** [Urigo/meteor-client-bundler#25]
After running the install and successfully running the app iOS on the simulator, I tried to run 'react-native run-android' (with my device plugged in) and get:
````
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `../node_modules/react-native/packager/api/server/collections` from `/Users/kenono/apps/ReactNativeMeteorBoilerplate/src/App.js`: Directory /Users/kenono/apps/ReactNativeMeteorBoilerplate/node_modules/react-native/packager/api/server/collections doesn't exist
    at UnableToResolveError (/Users/kenono/apps/ReactNativeMeteorBoilerplate/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:488:5)
    at Promise.resolve.then (/Users/kenono/apps/ReactNativeMeteorBoilerplate/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:445:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.android.js`  99.0% (402/404), failed.
````

Can anybody replicate that?  Any suggestions?

**Comment by DAB0mB** [comment]
@kokokenada Meteor has a messed up environment, for example (if I ain't wrong) you the variable `__dirname` will give you something an unexpected path. Be careful when you deal with Meteor and paths. You've probably tried to resolve the `collections` module dynamically or using an alias, didn't you? Can you show me how you tried to resolve these? This is probably a Meteor with symlinks problem....

**Comment by kokokenada** [comment]
Thanks for the reply @DAB0mB .  This error happened for me when I cloned the boiler plate (https://github.com/DAB0mB/ReactNativeMeteorBoilerplate )  and tried the build.  The app I'm working has a few additional libraries and I went make to the boiler plate to try to isolate the problem.  I expected that the problem can be replicated just by trying to run Android from this repo.  Is that not the case?
