### ISSUE TITLE
Error from static-html

### ISSUE THREAD

**Issue by untsamphan** [Urigo/meteor-client-bundler#29]
I've got the following error while trying to create a client-bundle from a working Meteor project.

```
Errors prevented bundling:                    
While processing files with static-html (for target web.browser):
client/main.html:12: Expected <head> or <body> tag

/usr/local/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277
		throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
		^
```

Here is the whole session:-
```
samphan gray:~/src/btrapp$ meteor-client bundle --source=../better/
Created a new Meteor app in '/var/folders/16/x31xxbkx2lg9zb1hrcy21c4m0000gn/T/tmp-33798TtHmhEF3DFDV'.

To run your new app:                          
  cd /var/folders/16/x31xxbkx2lg9zb1hrcy21c4m0000gn/T/tmp-33798TtHmhEF3DFDV
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
                                              
Changes to your project's package version selections:
                                              
accounts-base                   added, version 1.2.17
accounts-facebook               added, version 1.1.1
accounts-oauth                  added, version 1.1.15
aldeed:browser-tests            added, version 0.1.1
autopublish                     removed from your project
barbatus:typescript             added, version 0.6.5_1
barbatus:typescript-compiler    added, version 0.9.5
barbatus:typescript-runtime     added, version 1.0.0
blaze-html-templates            removed from your project
coffeescript                    added, version 1.0.17
ddp-rate-limiter                added, version 1.0.7
dispatch:mocha                  added, version 0.4.1
dispatch:mocha-browser          added, version 0.0.4
email                           added, version 1.2.1
facebook-oauth                  added, version 1.3.0
less                            added, version 2.7.9
localstorage                    added, version 1.0.12
meteortoys:toykit               added, version 3.0.4
msavin:mongol                   added, version 2.0.1
npm-bcrypt                      added, version 0.9.2
oauth                           added, version 1.1.13
oauth2                          added, version 1.1.11
practicalmeteor:chai            added, version 2.1.0_1
practicalmeteor:loglevel        added, version 1.2.0_2
practicalmeteor:mocha           added, version 2.4.5_6
practicalmeteor:mocha-core      added, version 1.0.1
practicalmeteor:sinon           added, version 1.14.1_2
rate-limit                      added, version 1.0.8
react-meteor-data               added, version 0.2.11
reactive-dict                   added, version 1.1.8
service-configuration           added, version 1.0.11
session                         added, version 1.1.7
simple:dev-error-overlay        added, version 1.5.1
softwarerero:accounts-t9n       added, version 1.3.9
static-html                     added, version 1.2.2
std:accounts-ui                 added, version 1.2.20
tmeasday:check-npm-versions     added, version 0.3.1
tmeasday:test-reporter-helpers  added, version 0.2.1

                                              
WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output
                                              
Errors prevented bundling:                    
While processing files with static-html (for target web.browser):
client/main.html:12: Expected <head> or <body> tag

/usr/local/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277
		throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
		^

Error: null
    at Function.module.exports.sync (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277:26)
    at Object.bundle (/usr/local/lib/node_modules/meteor-client-bundler/lib/bundler.js:79:9)
    at Command.<anonymous> (/usr/local/lib/node_modules/meteor-client-bundler/cli:42:13)
    at Command.listener (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-client-bundler/cli:50:9)
    at Module._compile (module.js:570:32)
```

And this is the usual client/main.html :- 
```html
<head>
  <meta charset="utf-8" />
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="css/onsenui.css">
  <link rel="stylesheet" href="css/onsen-css-components.css">
  <link rel="stylesheet" href="main.css">

  <title>Better</title>

  <style>
  </style>

</head>

<body>
  <div id="app-root"></div>
  <div id="popup"></div>
</body>
```

**Comment by vephinx** [comment]
I get the same error. Did you find a solution for this? Thanks.

**Comment by ardatan** [comment]
Run
‘meteor remove static-html’ in your Meteor project
