### ISSUE TITLE
package.json not in path when run meteor-client commend

### ISSUE THREAD

**Issue by sreejithsrk** [Urigo/meteor-client-bundler#30]
Hi,

I'm trying to use the Meteor some features to  my app, but I'm getting the following error when using meteor client bundler 

`
C:\Users\Sreejith P>meteor-client --help
C:\Users\Sreejith P\node_modules\meteor-client-bundler\node_modules\find-root\index.js:13
throw new Error('package.json not found in path')
    ^

Error: package.json not found in path
    at findRoot (C:\Users\Sreejith P\node_modules\meteor-client-bundler\node_modules\find-root\index.js:13:11)
    at findRoot (C:\Users\Sreejith P\node_modules\meteor-client-bundler\node_modules\find-root\index.js:21:10)
    at findRoot (C:\Users\Sreejith P\node_modules\meteor-client-bundler\node_modules\find-root\index.js:21:10)
    at findRoot (C:\Users\Sreejith P\node_modules\meteor-client-bundler\node_modules\find-root\index.js:21:10)
    at findRoot (C:\Users\Sreejith P\node_modules\meteor-client-bundler\node_modules\find-root\index.js:21:10)
    at Object.<anonymous> (C:\Users\Sreejith P\node_modules\meteor-client-bundler\lib\bundler.js:16:15)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)`

I have properly installed **meteor-client-bundler** on my system using "npm install -g meteor-client-bundler" and after I have run "meteor-client --help" I am getting above error.

I am using Windows 10 and Node.js version 7.00 

What could be the issue?

**Comment by mvandenbrink** [comment]
You need to run the meteor-client-bundler in a meteor directory. There should always be a package.json file in there. See https://angular-meteor.com/tutorials/whatsapp2/ionic/meteor-server-side for more information about how to use this package.

At a side note: to display help you don't need to have a package.json file. Maybe we can fix this.

**Comment by dCremins** [comment]
Ditto to the above error.
```
iMAC-422:~ itre$ npm install -g meteor-client-bundler
/usr/local/bin/meteor-client -> /usr/local/lib/node_modules/meteor-client-bundler/cli
+ meteor-client-bundler@0.2.1
added 72 packages in 7.016s
iMAC-422:~ itre$ meteor-client --help
/usr/local/lib/node_modules/meteor-client-bundler/node_modules/find-root/index.js:19
    throw new Error('package.json not found in path')
    ^

Error: package.json not found in path
    at findRoot (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/find-root/index.js:19:11)
    at findRoot (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/find-root/index.js:28:10)
    at findRoot (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/find-root/index.js:28:10)
    at findRoot (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/find-root/index.js:28:10)
    at findRoot (/usr/local/lib/node_modules/meteor-client-bundler/node_modules/find-root/index.js:28:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/meteor-client-bundler/lib/bundler.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by dCremins** [comment]
Sorry, here's my computer set up info 
node -v: v8.1.4
npm -v: 5.0.3
OS: osx el capitan v10.11.6

**Comment by darkbasic** [comment]
Closing due to inactivity and cleanup.
Feel free to open a new issue if you are still affected.
