### ISSUE TITLE
Bundle command doesn't run - Bash for windows

### ISSUE THREAD

**Issue by Zeioth** [Urigo/meteor-client-bundler#45]
Hi, I'm experiencing an error trying to run meteor-client-bundler in 'bash for Windows'. I can't even run:

    meteor-client-bundler --version

It shows the next error.

```
/usr/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277
                          throw (result.error || new Error (result.stderr === '' ? result.stdout : result.stderr));
                          ^

Error: spawnSync meteor ENOENT
    at exports._errnoException (util.js:1020:11)
    at spawnSync (child_process.js:450:20)
    at Function.module.exports.sync (/usr/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:274:30)
    at Object.bundle (/usr/lib/node_modules/meteor-client-bundler/lib/bundler.js:35:9)
    at Command.<anonymous> (/usr/lib/node_modules/meteor-client-bundler/cli:42:13)
    at Command.listener (/usr/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:106:13)
    Command.emit (events.js:191:7)
    Command.parseArgs (/usr/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:635:12)
    Command.parse (/usr/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:457:21)
```
Could you please try to reproduce it? My version of meteor-client-bundler version is **v0.2.1**. Thank you.

**Comment by vv001** [comment]
Hello, I am running into this issue as well on macos high sierra. Have you been able to resolve it by any chance?

**Comment by Urigo** [comment]
@vv001 are you still facing that issue with the new version?
