### ISSUE TITLE
meteor-client-bundler is incompatible with LicenseWebpackPlugin

### ISSUE THREAD

**Issue by darkbasic** [Urigo/meteor-client-bundler#47]
`angular-cli` uses `LicenseWebpackPlugin` when building for production:
```
    new LicenseWebpackPlugin({
      "licenseFilenames": [
        "LICENSE",
        "LICENSE.md",
        "LICENSE.txt",
        "license",
        "license.md",
        "license.txt"
      ],
      "perChunkOutput": false,
      "outputTemplate": "/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/output.template.ejs",
      "outputFilename": "3rdpartylicenses.txt",
      "suppressErrors": true,
      "includePackagesWithoutLicense": false,
      "abortOnUnacceptableLicense": false,
      "addBanner": false,
      "bannerTemplate": "/*! 3rd party license information is available at <%- filename %> */",
      "includedChunks": [],
      "excludedChunks": [],
      "additionalPackages": [],
      "pattern": /^(MIT|ISC|BSD.*)$/
    }),
```

Unfortunately this causes the following error:
```
$ npm run start

> angularcli-meteor@0.0.0 start /home/niko/WebstormProjects/angularcli-meteor
> webpack-dev-server --port=4200

 10% building modules 3/3 modules 0 activeProject is running at http://localhost:4200/
webpack output is served from /
404s will fallback to /index.html
 95% emittingUnhandled rejection Error: ENOTDIR: not a directory, open '/home/niko/WebstormProjects/angularcli-meteor/node_modules/meteor-client.js/package.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at LicenseExtractor.readPackageJson (/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/LicenseExtractor.js:121:23)
    at LicenseExtractor.parsePackage (/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/ModuleProcessor.js:21:21)
    at moduleCallback (/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:80:61)
    at Set.forEach (native)
    at Chunk.forEachModule (/home/niko/WebstormProjects/angularcli-meteor/node_modules/webpack/lib/Chunk.js:159:17)
    at /home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:88:27
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (/home/niko/WebstormProjects/angularcli-meteor/node_modules/license-webpack-plugin/dist/LicenseWebpackPlugin.js:65:32)
    at next (/home/niko/WebstormProjects/angularcli-meteor/node_modules/tapable/lib/Tapable.js:204:14)
    at /home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/index.js:204:9
    at PassThroughHandlerContext.finallyHandler (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/niko/WebstormProjects/angularcli-meteor/node_modules/html-webpack-plugin/node_modules/bluebird/js/release/async.js:143:10)
```

Commenting out `import 'meteor-client';` from `src/main.ts` solves the building issue, but obviously the app will not work.

You can easily reproduce the issue checking out my [angularcli-meteor tutorial repository](https://github.com/darkbasic/angularcli-meteor).

**Comment by DAB0mB** [comment]
Looks like this plugin assumes that every FS entity placed in the `node_modules` dir is a dir containing a `package.json` file. Maybe it would be a good idea to create a pull request for `LicenseWebpackPlugin`? Doesn't seem like a fix which is too hard to implement

**Comment by darkbasic** [comment]
Let's see what xz64 has to say about it, yesterday I also filed a bug report [upstream](https://github.com/xz64/license-webpack-plugin/issues/18).

**Comment by darkbasic** [comment]
There is a fix in the dev branch, thanks for your help.
