### ISSUE TITLE
Bundler failing 

### ISSUE THREAD

**Issue by megaslimegod** [Urigo/meteor-client-bundler#50]
After using the bundler regularly, now I am getting; 

F:\projects\meteor-switcher>meteor-client bundle --config=meteor-client.config.prod.json --destination=client/meteor/meteor-prod-client.js
C:\Users\rober\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: Error: Could not install npm dependencies for test-packages: Command failed: C:\WINDOWS\system32\cmd.exe /c C:\Users\rober\AppData\Local\.meteor\packages\meteor-tool\1.6.0_1\mt-os.windows.x86_64\dev_bundle\bin\npm.cmd install
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/meteor/readable-stream.git
npm ERR!
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rober\AppData\Roaming\npm-cache\_logs\2017-12-09T12_41_24_987Z-debug.log
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/meteor/readable-stream.git
npm ERR!
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rober\AppData\Roaming\npm-cache\_logs\2017-12-09T12_41_24_987Z-debug.log

    at Object.error (C:\tools\utils\buildmessage.js:430:11)
    at C:\tools\cli\default-npm-deps.js:32:20
    at C:\tools\utils\buildmessage.js:334:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:333:36
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.install (C:\tools\cli\default-npm-deps.js:27:27)
    at Command.func (C:\tools\cli\commands.js:799:36)
    at C:\tools\cli\main.js:1522:15
C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\node_modules\execa\index.js:277
                throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
                ^

Error: null
    at Function.module.exports.sync (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\node_modules\execa\index.js:277:26)
    at Object.bundle (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\lib\bundler.js:61:9)
    at Command.<anonymous> (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\cli:47:13)
    at Command.listener (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\node_modules\commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\node_modules\commander\index.js:653:12)
    at Command.parse (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\node_modules\commander\index.js:475:21)
    at Object.<anonymous> (C:\Users\rober\AppData\Roaming\nvm\v8.9.3\node_modules\meteor-client-bundler\cli:55:9)
    at Module._compile (module.js:635:30)

Environment is Windows 10, with NVM, Node 8.9.3 (new install), and Git version 2.13.1.windows.2.

How do I go about fixing this?

**Comment by megaslimegod** [comment]
Ok, I fixed this by upgrading my git installation to 2.15.1.windows.2.
