### ISSUE TITLE
SyntaxError in new projects 

### ISSUE THREAD

**Issue by dc165015** [Urigo/meteor-client-bundler#68]
When I created new meteor projects under meteor release 1.7.0.3/1.7.0.4/1.7.1, all will report this error while running command meteor-client bundle.

/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /var/folders/yk/dk4tpyws2dxc9_k2gjdllnrh0000gn/T/tmp-68935rRBl5k0h77bp/bundle/programs/web.browser/packages/srp.js: Unexpected token (1407:14)
  1405 |     return _defaults;
  1406 |
> 1407 |   var ret = { ..._defaults };
       |               ^
  1408 |
  1409 |   ['N', 'g', 'k'].forEach(function (p) {
  1410 |     if (options[p]) {
    at Parser.pp$5.raise (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/dc/.meteor/packages/meteor-tool/.1.7.0_4.10zz7at.hn36++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/meteor-client-bundler/node_modules/babylon/lib/index.js:3381:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bn2@0.0.1 meteor-client:bundle: `meteor-client bundle -s api -c meteor-client.config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bn2@0.0.1 meteor-client:bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dc/.npm/_logs/2018-08-08T07_51_33_107Z-debug.log

**Comment by ardatan** [comment]
Could you reproduce a repo?

**Comment by dc165015** [comment]
I am trying to uninstall all meteor and npm pkgs and do it again. if that fails again, I will upload that repo.

**Comment by katusiky** [comment]
me too. i cant resolve this

**Comment by dc165015** [comment]
I spent almost 1 day to reinstall meteor, downloading meteor is VERY slow and easily to be BROKEN here in China. 
I am sure it comes from the bundler. Before runs meteor-client-bundler, the src of ~/.meteor/packages/srp/1.0.10/os-legacy/packages/srp.js (Line#1383) is `var ret = _.extend({},` _defaults);  
After runs meteor-client-bundler, the compiled src became: /var/folders/yk/dk4tpyws2dxc9_k2gjdllnrh0000gn/T/tmp-68935rRBl5k0h77bp/bundle/programs/web.browser/packages/srp.js(Line#1407):  ` var ret = { ..._defaults };`

the complied src did have this error.

**Comment by kombadzomba** [comment]
Here too. It just started to happen few days ago.

**Comment by kombadzomba** [comment]
Please help. Provide some kind of workaround at least. This is a big blocker for us. We can not deploy new app versions without meteor client bundle and the oddest thing is that these kind of blocking errors just occur out of nowhere and we can not do much about it.

**Comment by kombadzomba** [comment]
Workaround:
`meteor add srp@=1.0.10`
Then edit `meteor-client-config.json` and add `srp@=1.0.10` to import.

**Comment by dc165015** [comment]
@kombadzomba  you save my day.

**Comment by dc165015** [comment]
In case of missing core-js related to this meteor-client-bundler,  there is another [patch](https://github.com/Urigo/angular-meteor/issues/1941#issuecomment-411521477)

**Comment by katusiky** [comment]
for me not work.

now the error is:
`/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277
                throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
                ^

Error: null
    at Function.module.exports.sync (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/node_modules/execa/index.js:277:26)
    at Object.bundle (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/lib/bundler.js:105:13)
    at Command.<anonymous> (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/cli:47:13)
    at Command.listener (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:651:12)
    at Command.parse (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/jose/.nvm/versions/node/v8.9.4/lib/node_modules/meteor-client-bundler/cli:55:9)
    at Module._compile (module.js:643:30)`

**Comment by kombadzomba** [comment]
@katusiky you have some other issue, I suppose related to:
https://github.com/Urigo/meteor-client-bundler/issues/17

It seems that you have installed meteor-client-bundler globaly. I'm using it as dev package, project related. Check if you are using the latest version of the package and clear the NPM cache.

**Comment by KeithGillette** [comment]
We are also experiencing this error under `meteor-client-bundler@0.5.0` on a Meteor@1.7.0.1 project with Meteor 1.7.0.4 global install. I was able to get `meteor-client-bundler` to work again after:
```
meteor reset
rm -rf node_modules
rm -rf ~/.meteor
rm -rf ~/.meteorsession
npm install
``

**Comment by ardatan** [comment]
It is now `0.5.9`. Please update `meteor-client-bundler` and try again.
